language: php

php:
  - 5.3
  - 5.4
  - 5.5
  - 5.6

before_script:
  - sudo apt-get update
  - sudo apt-get install libssh2-1-dev libssh2-php
  - touch .noninteractive && pecl install -f ssh2 < .noninteractive
  - sudo useradd shunt
  - sudo passwd shunt < .shuntpwd
  - sudo mkdir /home/shunt
  - sudo chown shunt:shunt /home/shunt
  - sudo usermod -d /home/shunt shunt
  - composer install

script: phpunit --configuration travis.xml.dist
